name: local
variables:
  - name: baseUrl
    value: http://127.0.0.1:3000
  - name: summarizeDirName
    value: albums/1-source-files/Across The Universe Soundtrack
  - name: albumListPrefix
    value: ''
  - name: albumListNestedPrefix
    value: albums/
  - name: scratchAlbumEntry
    value: scratch-only/
  - name: albumOrganizeDir
    value: albums/1-source-files/Across The Universe Soundtrack/
  - name: ignoreNonAudioFiles
    value: 'true'
  - name: traversalDirName
    value: ..
  - name: sampleAlbumFileName
    value: albums/1-source-files/Across The Universe Soundtrack/1-01 Girl.mp3
  - name: graphqlAlbumDirName
    value: albums/1-source-files/Across The Universe Soundtrack
  - name: graphqlAudiobookDirName
    value: audiobooks
  - name: graphqlAudiobookFileName
    value: audiobooks/2-aggregated-files/metadata-corrected/Michael Kimmel - Angry White Men.m4b
  - name: graphqlMetadataDestFilepath
    value: audiobooks/2-aggregated-files/metadata-corrected/GraphQL dry run.m4b
  - name: mcpProtocolVersion
    value: '2025-11-25'
