name: local
variables:
  - name: baseUrl
    value: http://127.0.0.1:3000
  - name: summarizeDirName
    value: .
  - name: ignoreNonAudioFiles
    value: 'true'
  - name: traversalDirName
    value: ..
  - name: sampleAlbumFileName
    value: StarTropics/Y. Hirai - StarTropics OST - 01 - Opening.mp3
